#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-eco
Version  : 1.0.0
Release  : 5
URL      : https://rubygems.org/downloads/eco-1.0.0.gem
Source0  : https://rubygems.org/downloads/eco-1.0.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-coffee-script
BuildRequires : rubygem-eco-source
BuildRequires : rubygem-execjs
BuildRequires : rubygem-rdoc

%description
Ruby Eco
========
Ruby Eco is a bridge to the official
[Eco](https://github.com/sstephenson/eco) compiler for embedded
CoffeeScript templates.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n eco-1.0.0
gem spec %{SOURCE0} -l --ruby > rubygem-eco.gemspec

%build
gem build rubygem-eco.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
eco-1.0.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/eco-1.0.0.gem
/usr/lib64/ruby/gems/2.3.0/gems/eco-1.0.0/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/eco-1.0.0/README.md
/usr/lib64/ruby/gems/2.3.0/gems/eco-1.0.0/lib/eco.rb
/usr/lib64/ruby/gems/2.3.0/specifications/eco-1.0.0.gemspec
